# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398ada2a9c71ffc0421637c70da0bd0b6bb3aa12713ab4fa07d30bc460a7a08f40f0f7a5d27ee4bb3727fb1d3cddb1504b8b0fcefc64deedbfeaa6eab809f868

test:
  secret_key_base: 219f2848b36a5ab43cb35976fc0f467e8cfe515784445de359e342c3eba05e63735006f8f8934a154aed0dc3bc431ad813d411512a634b7a515d331b0f2e402a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
